// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuO9su6uUbMl0pa__NkTVUp8Ee0ay1X1o',
    appId: '1:577606194223:web:e24d760e4ab02d2b0522da',
    messagingSenderId: '577606194223',
    projectId: 'food-oasis-fbab6',
    authDomain: 'food-oasis-fbab6.firebaseapp.com',
    storageBucket: 'food-oasis-fbab6.firebasestorage.app',
    measurementId: 'G-RZ49W1QQ5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYzR7Sb7YwIzPmAfwlAafSH4rQOW_mUTk',
    appId: '1:577606194223:android:2ec36b22032a0d890522da',
    messagingSenderId: '577606194223',
    projectId: 'food-oasis-fbab6',
    storageBucket: 'food-oasis-fbab6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEEeDO1F9wPMYgE_nQ3Rh1xPxv2FN7W84',
    appId: '1:577606194223:ios:3738571904195de80522da',
    messagingSenderId: '577606194223',
    projectId: 'food-oasis-fbab6',
    storageBucket: 'food-oasis-fbab6.firebasestorage.app',
    iosBundleId: 'com.example.foodOasis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEEeDO1F9wPMYgE_nQ3Rh1xPxv2FN7W84',
    appId: '1:577606194223:ios:3738571904195de80522da',
    messagingSenderId: '577606194223',
    projectId: 'food-oasis-fbab6',
    storageBucket: 'food-oasis-fbab6.firebasestorage.app',
    iosBundleId: 'com.example.foodOasis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuO9su6uUbMl0pa__NkTVUp8Ee0ay1X1o',
    appId: '1:577606194223:web:c026e1b986c8491f0522da',
    messagingSenderId: '577606194223',
    projectId: 'food-oasis-fbab6',
    authDomain: 'food-oasis-fbab6.firebaseapp.com',
    storageBucket: 'food-oasis-fbab6.firebasestorage.app',
    measurementId: 'G-XK3Y4144Z5',
  );
}
