/* Fake data for testing page functionality */

final List<Map<String, dynamic>> shopItems = [
  {
    'id': '1',
    'name': 'Organic Apple Bundle',
    'seller': 'Fresh Harvest Market',
    'price': 6.99,
    'description': 'B undle of 6 locally grown apples. Crisp and sweet.',
    'tags': ['organic', 'fruit', 'local'],
    'imageIcon': 'apple',
  },
  {
    'id': '2',
    'name': 'Green Goddess Bowl',
    'seller': 'Green Leaf Cafe',
    'price': 12.99,
    'description': 'Bowl with quinoa, avocado, kale, chickpeas, and tahini dressing. Vegan and gluten-free.',
    'tags': ['vegan', 'gluten-free', 'bowl'],
    'imageIcon': 'lunch_dining',
  },
  {
    'id': '3',
    'name': 'Sunrise Detox Juice',
    'seller': 'Sunrise Juice Co.',
    'price': 8.49,
    'description': 'Cold-pressed juice with apple, ginger, lemon, and turmeric.',
    'tags': ['juice', 'cold-pressed', 'detox'],
    'imageIcon': 'local_drink',
  },
  {
    'id': '4',
    'name': 'Weekly Meal Prep Box',
    'seller': 'Urban Farm Kitchen',
    'price': 49.99,
    'description': '5 ready-to-heat meals made with locally grown ingredients.',
    'tags': ['meal prep', 'farm-to-table', 'fresh'],
    'imageIcon': 'takeout_dining',
  },
  {
    'id': '5',
    'name': 'Whole Grain Sourdough',
    'seller': 'Golden Grain Bakery',
    'price': 7.99,
    'description': 'Sourdough loaf made with whole grain flour. Low sugar, high fiber.',
    'tags': ['bread', 'whole grain', 'low sugar'],
    'imageIcon': 'bakery_dining',
  },
  {
    'id': '6',
    'name': 'Vegan Energy Bites',
    'seller': 'Plant-Based Bites',
    'price': 5.99,
    'description': 'Pack of 8 energy bites made with oats, dates, and cacao.',
    'tags': ['vegan', 'snack', 'healthy'],
    'imageIcon': 'cookie',
  },
  {
    'id': '7',
    'name': 'Farm Fresh Eggs',
    'seller': 'Fresh Harvest Market',
    'price': 5.49,
    'description': 'Dozen pasture-raised eggs from local farms.',
    'tags': ['organic', 'protein', 'local'],
    'imageIcon': 'egg',
  },
  {
    'id': '8',
    'name': 'Berry Blast Smoothie',
    'seller': 'Green Leaf Cafe',
    'price': 9.99,
    'description': 'Blended smoothie with mixed berries, banana, almond milk, and plant protein.',
    'tags': ['smoothie', 'vegan', 'protein'],
    'imageIcon': 'blender',
  },
];